vfit:
  api-key: sk_test_eMJA07HTa4ephNA3lR42CuHG00k6gjNgTz
  liveMode: true

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?charSet=LATIN1
    username: vFitUser
    password: vFitPassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update